name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: |
        python -m build

    - name: Check package
      run: |
        twine check dist/*

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        draft: true
        generate_release_notes: true
        body: |
          ## Release Notes
          
          This is an automated release draft. Please:
          1. Review the generated release notes
          2. Add any additional context or breaking changes
          3. Publish the release when ready
          
          ## Installation
          
          ```bash
          pip install raglib==${{ github.ref_name }}
          ```
          
          ## Files
          - `raglib-*.tar.gz` - Source distribution
          - `raglib-*.whl` - Python wheel
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to PyPI
      if: ${{ !contains(github.ref, 'rc') && !contains(github.ref, 'dev') }}
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*
